### ISSUE TITLE
Criar um baseUrl para a aplicação

### ISSUE THREAD

**Issue by mikaelhadler** [erikvix/MERN-Stack-DashBoard#3]
## O que está acontecendo?
Hoje a aplicação utiliza um padrão na url com a palavra `/api` antes de todas as rotas

## O que é esperado?
Eu espero que seja registrado como base url a palavra `/api`

Então, o resultado esperado é que o base url seja registrado como um padrão da url e as outras requisições não precisem declarar elas nas suas rotas

```javascript
GET /user 
// e não /api/user dentro do arquivo de rotas de user.
```

Obs: as rotas de `/user` só devem conter user, nada mais.

Exemplo
```javascript
// routes/user.js
let express = require('express');
let router = express.Router();

router.get('/users', (req, res) => {
    // ...
});
router.get('/user/:id', (req, res) => {
    // ...
});
module.exports = router;

// routes/index.js

app.use('/api', require('./user'));

// server/server.js
// Você irá carregar o routes/index.js

```

**Comment by erikvix** [comment]
Resolvido no commit: 00b8af4
